# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Sayer": "Modelling.ipynb",
         "sy": "Modelling.ipynb"}

modules = ["card.py"]

doc_url = "https://Puneet.github.io/mllib/"

git_url = "https://github.com/Puneet/mllib/tree/main/"

def custom_doc_links(name): return None
